replicaCount: 2

image:
  repository: abdullahtarar222/demo-node-app
  tag: directory-app
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/load-balancer-type: "nlb"   # ✅ Use NLB instead of ALB
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
  hosts:
    - host: "abdullah-node-app.mooo.com"
      paths:
        - path: "/"
          pathType: "Prefix"



serviceAccount:
  create: true
  name: "node-app-sa"
