replicaCount: 2

image:
  repository: abdullahtarar222/demo-node-app
  tag: directory-app
  pullPolicy: Always


service:
  name: node-app-service
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  port: 80
  targetPort: 5000
  selector:
    app: node-app

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
