replicaCount: 2

image:
  repository: abdullahtarar222/demo-node-app
  tag: directory-app
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: "node-app-alb"
  hosts:
    - host: "*"
      paths:
        - path: "/"
          pathType: "Prefix"

serviceAccount:
  create: true
  name: "node-app-sa"
