apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  # ✅ Use service name from values.yaml
  labels:
    app: node-app
spec:
  type: {{ .Values.service.type }}  # ✅ Use NodePort instead of LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # ✅ Exposed port (matches ingress)
      targetPort: {{ .Values.service.targetPort }}  # ✅ Internal pod port
